# XBSV
# version 0.1

From ubuntu
Maintainer Jamey Hicks <jamey.hicks@qrclab.com>

RUN mkdir -p /scratch/bluespec
ADD http://localhost/scratch/bluespec/Bluespec-2014.05.beta1.tar.gz /scratch/bluespec/Bluespec-2014.05.beta1.tar.gz
RUN tar -zxf /scratch/bluespec/Bluespec-2014.05.beta1.tar.gz
