# XBSV
# version 0.1

From centos:centos7
Maintainer Jamey Hicks <jamey.hicks@qrclab.com>
ADD android-ndk-r9d.tar.gz /scratch/
#ADD Bluespec-2014.07.A.tar.gz /scratch/bluespec/
ADD Bluespec-2014.05.beta1.tar.gz /scratch/bluespec/
ADD vivado-2014.1.tar.gz /scratch/Xilinx/Vivado/
VOLUME /scratch/bluespec
VOLUME /scratch/android-ndk-r9d
VOLUME /scratch/Xilinx

